import {
	AppWindow,
	Bot,
	Clapperboard,
	Cloud,
	Cog,
	Database,
	GraduationCap,
	Hash,
	Layers,
	LayoutGrid,
	type LucideIcon,
	Monitor,
	MonitorSmartphone,
	Newspaper,
	Package,
	Palette,
	PenTool,
	Puzzle,
	Server,
	ShieldCheck,
	Smartphone,
	Table,
	Terminal,
	TrendingUp,
	Wrench,
	Zap,
} from "lucide-react";

const CATEGORY_ICONS: Record<string, LucideIcon> = {
	ai: Bot,
	automation: Zap,
	backend: Server,
	"browser-extensions": Puzzle,
	cli: Terminal,
	cloud: Cloud,
	"content-cms": Newspaper,
	databases: Database,
	data: Table,
	"data-visualization": TrendingUp,
	design: Palette,
	"design-systems": Layers,
	desktop: Monitor,
	"developer-tools": Wrench,
	devops: Cog,
	dotnet: Hash,
	"editor-tooling": PenTool,
	frontend: AppWindow,
	learning: GraduationCap,
	libraries: Package,
	media: Clapperboard,
	misc: MonitorSmartphone,
	mobile: Smartphone,
	security: ShieldCheck,
};

export function categoryIcon(categoryId: string): LucideIcon {
	return CATEGORY_ICONS[categoryId] ?? LayoutGrid;
}
